### ISSUE TITLE
Modifying ItemsSource while swiping

### ISSUE THREAD

**Issue by taylorrobert** [markolazic88/SwipeCardView#12]
My use case is this: the swipe direction of the current top item determines which item is added to the collection next, then removes the previous one, such that there is only one thing ever in the collection. It seems to get confused with this and causes a null reference error when removing the old item from the collection. Is there any way to implement my use case?

**Comment by markolazic88** [comment]
It seems to that an ideal control for your use case would be one without stack of cards nor ItemsSource collection binding, but rather to have only one card and only singular ItemSource binding. That way the control would null ItemSource whenever swiped, and you would set it to a new value in the event handlers.

Since that control probably doesn't exist, you should be able to do the job with SwipeCardView too. I am not able dive into the code currently, but I bet that null reference exception could be fixed. Maybe you could include SwipeCardView code into you solution and debug it for your use case?

**Comment by taylorrobert** [comment]
That makes sense. I will delve into it and see if I can modify the API to allow a singular ItemsSource rather than a collection. If I do, I will submit a pull request. Thanks! Your control is wonderful.
