### ISSUE TITLE
Index out of range Exception

### ISSUE THREAD

**Issue by visualbruno** [markolazic88/SwipeCardView#14]
Hi

I assigned a simple ObservableCollection<Product> to ItemsSource, and I soon as I swap a card, it crashes.

Error is in SwipeCardView.cs
Method: ShowNextCard()
Line: this.TopItem = this.ItemsSource[_itemIndex-1]; --> out of range exception

I only found a way to fix the issue by changing the code like this:

Instead of this.TopItem = this.ItemsSource[_itemIndex-1];

			if (_itemIndex == 0)
				_itemIndex = 1;

			this.TopItem = this.ItemsSource[_itemIndex];
			_itemIndex++;

And remove at the end of the method: _itemIndex++;

Regards
Bruno

Full method here:
        private void ShowNextCard()
        {
            if (_cards[0].IsVisible == false && _cards[1].IsVisible == false)
            {
                this.Setup();
                return;
            }

			if (_itemIndex == 0)
				_itemIndex = 1;

			this.TopItem = this.ItemsSource[_itemIndex];
			_itemIndex++;

            var topCard = _cards[_topCardIndex];
            _topCardIndex = this.NextCardIndex(_topCardIndex);

            // If there are more cards to show, show the next card in to place of 
            // the card that was swiped off the screen
            if (_itemIndex < this.ItemsSource.Count)
            {
                // Push it to the back z order
                ((RelativeLayout)this.Content).LowerChild(topCard);

                try
                {
                    // Reset its scale, opacity and rotation
                    topCard.Scale = BackCardScale;
                    topCard.RotateTo(0, 0);
                    topCard.TranslateTo(0, -topCard.Y, 0);
                }
                catch (Exception exception)
                {
                    Debug.WriteLine(exception);
                }

                topCard.BindingContext = this.ItemsSource[_itemIndex];

                topCard.IsVisible = true;
            }
        }

**Comment by markolazic88** [comment]
Thanks Bruno! I added your suggestion into dev-2.1 branch.

**Comment by visualbruno** [comment]
> Thanks Bruno! I added your suggestion into dev-2.1 branch.

Maybe there is a better way to fix it. I did not read all your code, maybe the error comes from the Setup.

Regards
Bruno

**Comment by antonmagnus** [comment]
> Maybe there is a better way to fix it. I did not read all your code, maybe the error comes from the Setup.

@visualbruno make sure you are not removing the item from the ObservableCollection when swipe command is Invoked as that is handled by the ShowNextCard method. If the item has already been removed when ShowNextCard is called that will result in an index out of range exception.

**Comment by markolazic88** [comment]
This issue should be fixed in 2.1.0 release. 

ItemsSource setter had a tricky statement which was setting internal _itemIndex to 0, which was occurring after the control already went through Setup() method. It seems that this setter is being called only when ItemsSource is set from code behind. If ItemsSource is set in XAML then OnItemsSourcePropertyChanged is being invoked, and not the setter. Since all of my examples were using XAML, this issue went unnoticed for a long time.

The other possible cause for this issue could be the changes in Xamarin Forms since version 3.0.0. I noticed an exception in development when targeting both XF 3.0 and 4.0+ in the same solution. So I updated the minimal Xamarin.Forms dependency to 4.2.0.848062. By now most of the people are already on this version, or newer.
